version: '3.1'

volumes:
  postgres_data_prod: {}
  postgres_backup_prod: {}

services:
  # =============================================================
  # Webapp
  # =============================================================
  dolo:
    image: loitrinh/django:0.1.0
    container_name: web
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-prod
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=dolo_app
      - POSTGRES_HOST=postgres
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    ports:
      - "5000:5000"
    command: /start-prod.sh

  # =============================================================
  # Postgres
  # =============================================================
  postgres:
    image: loitrinh/postgres:0.1.0
    container_name: database
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - postgres_backup_prod:/backups
    environment:
      - POSTGRES_USER=dolo_app
      - POSTGRES_HOST=postgres

  # =============================================================
  # Redis
  # =============================================================
  redis:
    image: redis:latest
    container_name: redis

  # =============================================================
  # Nginx
  # =============================================================
  nginx:
    image: loitrinh/nginx:0.1.0
    container_name: nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - dolo



