version: '3.1'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  # =============================================================
  # Webapp
  # =============================================================
  web:
    image: loitrinh/django:0.1.0
    container_name: web-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=dolo_app
      - POSTGRES_HOST=postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
    ports:
      - "5000:8000"
    command: /start.sh

  # =============================================================
  # Postgres
  # =============================================================
  postgres:
    image: loitrinh/postgres:0.1.0
    container_name: postgres-dev
    build: ./../compose/postgres/
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_USER=dolo_app
      - POSTGRES_HOST=postgres
